/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.terry.hermes;

public class Messenger {
    private int messagesDelivered = 0;

    public boolean deliverMessage() {
        messagesDelivered++;
        System.out.println("Hermes has delivered " + messagesDelivered + " messages.");

        return true;
    }
}
