/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.terry.hermes;

import org.junit.Test;
import static org.junit.Assert.*;

public class MessengerTest {
    @Test public void testSomeLibraryMethod() {
        Messenger classUnderTest = new Messenger();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.deliverMessage());
    }
}
